import { jsPDF } from "jspdf";
import { unitLabel, type BusinessUnit } from "../db";

export interface InvoiceItem {
  itemName: string;
  qty: number;
  price: number;
  unit?: BusinessUnit;
  measurementLabel?: string;
}

export interface InvoiceData {
  customerName: string;
  customerPhone?: string;
  items: InvoiceItem[];
  subtotal: number;
  gstEnabled: boolean;
  gstRate: number;
  cgst: number;
  sgst: number;
  grandTotal: number;
  businessName?: string;
  businessSubline?: string;
  workNote?: string;
}

function inr(n: number): string {
  return "Rs. " + n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function generateInvoicePDF(data: InvoiceData): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = 20;

  const business = data.businessName || "Kolkata Grill Works";
  const subline = data.businessSubline || "Steel Grill, Gate, Railing & Fabrication - Kolkata, West Bengal";

  // Header band
  doc.setFillColor(26, 115, 232);
  doc.rect(0, 0, pageW, 32, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(business, margin, 16);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(subline, margin, 23);
  doc.setFontSize(10);
  doc.text("TAX INVOICE", margin, 29);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  const dateStr = new Date().toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
  doc.text(`Date: ${dateStr}`, pageW - margin, 16, { align: "right" });
  doc.text(`Invoice #: ${Date.now().toString().slice(-8)}`, pageW - margin, 22, { align: "right" });

  y = 44;

  // Bill to
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("BILL TO", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(20, 20, 20);
  doc.text(data.customerName, margin, y + 6);
  if (data.customerPhone) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(data.customerPhone, margin, y + 11);
  }

  if (data.workNote) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(`Work / Site: ${data.workNote}`, margin, y + 16);
  }

  y += data.workNote ? 28 : 22;

  // Table header
  const colX = {
    item: margin,
    qty: pageW - margin - 75,
    price: pageW - margin - 45,
    total: pageW - margin,
  };

  doc.setFillColor(240, 244, 250);
  doc.rect(margin, y - 5, pageW - margin * 2, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(40, 40, 40);
  doc.text("ITEM", colX.item + 1, y);
  doc.text("QTY", colX.qty, y, { align: "right" });
  doc.text("RATE", colX.price, y, { align: "right" });
  doc.text("AMOUNT", colX.total, y, { align: "right" });

  y += 8;

  // Rows
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);
  data.items.forEach((it) => {
    const amt = it.qty * it.price;
    doc.text(it.itemName.slice(0, 34), colX.item + 1, y);
    if (it.measurementLabel) {
      doc.setFontSize(8);
      doc.setTextColor(110, 110, 110);
      doc.text(it.measurementLabel.slice(0, 42), colX.item + 1, y + 4);
      doc.setFontSize(9);
      doc.setTextColor(30, 30, 30);
    }
    doc.text(`${it.qty} ${unitLabel(it.unit)}`, colX.qty, y, { align: "right" });
    doc.text(inr(it.price), colX.price, y, { align: "right" });
    doc.text(inr(amt), colX.total, y, { align: "right" });
    y += it.measurementLabel ? 10 : 7;
    doc.setDrawColor(235, 235, 235);
    doc.line(margin, y - 3, pageW - margin, y - 3);
  });

  y += 4;

  // Totals block
  const labelX = pageW - margin - 50;
  const valX = pageW - margin;

  const addTotal = (label: string, value: string, bold = false) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(bold ? 12 : 10);
    doc.setTextColor(bold ? 26 : 60, bold ? 115 : 60, bold ? 232 : 60);
    doc.text(label, labelX, y, { align: "right" });
    doc.text(value, valX, y, { align: "right" });
    y += bold ? 9 : 6;
  };

  addTotal("Subtotal:", inr(data.subtotal));
  if (data.gstEnabled) {
    addTotal(`CGST (${data.gstRate / 2}%):`, inr(data.cgst));
    addTotal(`SGST (${data.gstRate / 2}%):`, inr(data.sgst));
  }
  doc.setDrawColor(200, 200, 200);
  doc.line(labelX - 5, y - 2, valX, y - 2);
  y += 3;
  addTotal("GRAND TOTAL:", inr(data.grandTotal), true);

  // Footer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(130, 130, 130);
  doc.text(
    "Thank you for your business! Generated by MeraKhata (offline).",
    margin,
    285
  );

  const safeName = data.customerName.replace(/[^a-z0-9]/gi, "_");
  doc.save(`invoice_${safeName}_${Date.now()}.pdf`);
}
